//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BITC.CMS.Data.Mapping
{
    public partial class BlogEntryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BITC.CMS.Data.Entity.BlogEntry>
    {
        public BlogEntryMap()
        {
            // table
            ToTable("BlogEntry", "dbo");

            // keys
            HasKey(t => t.BlogEntryID);

            // Properties
            Property(t => t.BlogEntryID)
                .HasColumnName("BlogEntryID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.BlogTitle)
                .HasColumnName("BlogTitle")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.Body)
                .HasColumnName("Body")
                .IsRequired();
            Property(t => t.Culture)
                .HasColumnName("Culture")
                .HasMaxLength(10)
                .IsRequired();
            Property(t => t.AllowComment)
                .HasColumnName("AllowComment")
                .IsRequired();
            Property(t => t.Inactive)
                .HasColumnName("Inactive")
                .IsRequired();
            Property(t => t.SortOrder)
                .HasColumnName("SortOrder")
                .IsOptional();
            Property(t => t.CreatedDate)
                .HasColumnName("CreatedDate")
                .IsOptional();
            Property(t => t.CreatedBy)
                .HasColumnName("CreatedBy")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsOptional();
            Property(t => t.ModifiedBy)
                .HasColumnName("ModifiedBy")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Source)
                .HasColumnName("Source")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.PublishDate)
                .HasColumnName("PublishDate")
                .IsOptional();

            // Relationships
            HasMany(t => t.BlogTags)
                .WithMany(t => t.BlogEntries)
                .Map(m =>
                {
                    m.ToTable("BlogEntriesInTag", "dbo");
                    m.MapLeftKey("BlogEntryID");
                    m.MapRightKey("BlogTagID");
                });

            InitializeMapping();
        }
    }
}

