//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BITC.CMS.Data.Mapping
{
    public partial class ClientMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BITC.CMS.Data.Entity.Client>
    {
        public ClientMap()
        {
            // table
            ToTable("Client", "dbo");

            // keys
            HasKey(t => t.ClientID);

            // Properties
            Property(t => t.ClientID)
                .HasColumnName("ClientID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.ClientName)
                .HasColumnName("ClientName")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.Logo)
                .HasColumnName("Logo")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.GrayscaleLogo)
                .HasColumnName("GrayscaleLogo")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Website)
                .HasColumnName("Website")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.SortOrder)
                .HasColumnName("SortOrder")
                .IsRequired();
            Property(t => t.CreatedDate)
                .HasColumnName("CreatedDate")
                .IsOptional();
            Property(t => t.CreatedBy)
                .HasColumnName("CreatedBy")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsOptional();
            Property(t => t.ModifiedBy)
                .HasColumnName("ModifiedBy")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Inactive)
                .HasColumnName("Inactive")
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}

