//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BITC.CMS.Data.Mapping
{
    public partial class NewsCategoryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BITC.CMS.Data.Entity.NewsCategory>
    {
        public NewsCategoryMap()
        {
            // table
            ToTable("NewsCategory", "dbo");

            // keys
            HasKey(t => t.NewsCategoryID);

            // Properties
            Property(t => t.NewsCategoryID)
                .HasColumnName("NewsCategoryID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.NewsCategoryName)
                .HasColumnName("NewsCategoryName")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.Slug)
                .HasColumnName("Slug")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.SortOrder)
                .HasColumnName("SortOrder")
                .IsRequired();
            Property(t => t.Inactive)
                .HasColumnName("Inactive")
                .IsRequired();
            Property(t => t.Culture)
                .HasColumnName("Culture")
                .HasMaxLength(10)
                .IsOptional();
            Property(t => t.CreatedDate)
                .HasColumnName("CreatedDate")
                .IsOptional();
            Property(t => t.CreatedBy)
                .HasColumnName("CreatedBy")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsOptional();
            Property(t => t.ModifiedBy)
                .HasColumnName("ModifiedBy")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Description).HasColumnName("Description").HasMaxLength(1000).IsOptional();

            // Relationships
            HasMany(t => t.News)
                .WithMany(t => t.NewsCategories)
                .Map(m =>
                {
                    m.ToTable("NewsInCategory", "dbo");
                    m.MapLeftKey("NewsCategoryID");
                    m.MapRightKey("NewsID");
                });

            InitializeMapping();
        }
    }
}

