//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BITC.CMS.Data.Mapping
{
    public partial class NewsMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BITC.CMS.Data.Entity.News>
    {
        public NewsMap()
        {
            // table
            ToTable("News", "dbo");

            // keys
            HasKey(t => t.NewsID);

            // Properties
            Property(t => t.NewsID)
                .HasColumnName("NewsID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.Title)
                .HasColumnName("Title")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.Body)
                .HasColumnName("Body")
                .IsRequired();
            Property(t => t.NewsImage)
                .HasColumnName("NewsImage")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.SortOrder)
                .HasColumnName("SortOrder")
                .IsOptional();
            Property(t => t.Inactive)
                .HasColumnName("Inactive")
                .IsRequired();
            Property(t => t.Status)
                .HasColumnName("Status")
                .IsRequired();
            Property(t => t.CreatedDate)
                .HasColumnName("CreatedDate")
                .IsOptional();
            Property(t => t.CreatedBy)
                .HasColumnName("CreatedBy")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsOptional();
            Property(t => t.ModifiedBy)
                .HasColumnName("ModifiedBy")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.ReadCount)
                .HasColumnName("ReadCount")
                .IsRequired();
            Property(t => t.PublishDate)
                .HasColumnName("PublishDate")
                .IsOptional();
            Property(t => t.AllowComment)
                .HasColumnName("AllowComment")
                .IsRequired();
            Property(t => t.Culture)
                .HasColumnName("Culture")
                .HasMaxLength(10)
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}

