//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BITC.CMS.Data.Mapping
{
    public partial class SettingMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BITC.CMS.Data.Entity.Setting>
    {
        public SettingMap()
        {
            // table
            ToTable("Setting", "dbo");

            // keys
            HasKey(t => t.SettingID);

            // Properties
            Property(t => t.SettingID)
                .HasColumnName("SettingID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.ModuleID)
                .HasColumnName("ModuleID")
                .IsOptional();
            Property(t => t.SettingKey)
                .HasColumnName("SettingKey")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.SettingValue)
                .HasColumnName("SettingValue")
                .IsOptional();

            // Relationships
            HasOptional(t => t.Module)
                .WithMany(t => t.Settings)
                .HasForeignKey(d => d.ModuleID);

            InitializeMapping();
        }
    }
}

