//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace BITC.CMS.Data.Entity
{
    public partial class BlogEntryComment
    {
        public BlogEntryComment()
        {
        }

        public int BlogEntryCommentID { get; set; }
        public int BlogEntryID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsAuthor { get; set; }

        public virtual BlogEntry BlogEntry { get; set; }
    }
}