using BITC.Library.Data;
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace BITC.CMS.Data.Entity
{
    public partial class Client : BaseEntity
    {
        public Client()
        {
        }

        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string Logo { get; set; }
        public string GrayscaleLogo { get; set; }
        public string Website { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Inactive { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}