using BITC.Library.Data;
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace BITC.CMS.Data.Entity
{
    public partial class Menu
    {
        public Menu()
        {
            Child = new List<Menu>();
        }

        public int MenuID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public int? ParentID { get; set; }
        public int SortOrder { get; set; }
        public bool Inactive { get; set; }
        public string Culture { get; set; }
        public System.DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Menu Parent { get; set; }
        public virtual ICollection<Menu> Child { get; set; }
    }
}