//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace BITC.CMS.Data.Entity
{
    public partial class Module
    {
        public Module()
        {
            Settings = new List<Setting>();
        }

        public System.Guid ModuleID { get; set; }
        public string ModuleName { get; set; }
        public bool Inactive { get; set; }
        public bool IsSystem { get; set; }
        public System.DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }

        public virtual ICollection<Setting> Settings { get; set; }
    }
}