//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace BITC.CMS.Data.Entity
{
    public partial class NewsCategory
    {
        public NewsCategory()
        {
            News = new List<News>();
        }

        public int NewsCategoryID { get; set; }
        public string NewsCategoryName { get; set; }

        public string Description { get; set; }

        public string Slug { get; set; }
        public int SortOrder { get; set; }
        public bool Inactive { get; set; }
        public string Culture { get; set; }
        public System.DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ICollection<News> News { get; set; }
    }
}