//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace BITC.CMS.Data.Entity
{
    public partial class News
    {
        public News()
        {
            NewsCategories = new List<NewsCategory>();
            NewsCategoriesID = new List<int>();
        }

        public int NewsID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string NewsImage { get; set; }
        public int? SortOrder { get; set; }
        public int Inactive { get; set; }
        public bool Status { get; set; }
        public System.DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public int ReadCount { get; set; }
        public System.DateTime? PublishDate { get; set; }
        public bool AllowComment { get; set; }
        public string Culture { get; set; }

        public virtual ICollection<NewsCategory> NewsCategories { get; set; }
    }
}