//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace BITC.CMS.Data.Entity
{
    public partial class Setting
    {
        public Setting()
        {
        }

        public int SettingID { get; set; }
        public System.Guid? ModuleID { get; set; }
        public string SettingKey { get; set; }
        public string SettingValue { get; set; }

        public virtual Module Module { get; set; }
    }
}