//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITC.CMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTag
    {
        public BlogTag()
        {
            this.BlogEntries = new HashSet<BlogEntry>();
        }
    
        public int BlogTagID { get; set; }
        public string TagName { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<BlogEntry> BlogEntries { get; set; }
    }
}
