//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITC.CMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogEntry
    {
        public BlogEntry()
        {
            this.BlogTags = new HashSet<BlogTag>();
        }
    
        public int BlogEntryID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Culture { get; set; }
        public bool AllowComment { get; set; }
        public bool Inactive { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<BlogTag> BlogTags { get; set; }
    }
}
