//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITC.CMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int MediaID { get; set; }
        public Nullable<int> MediaType { get; set; }
        public string MIMEType { get; set; }
        public string Caption { get; set; }
        public string AlternativeText { get; set; }
        public string Description { get; set; }
        public string Dimension { get; set; }
        public long FileSize { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string Author { get; set; }
        public string Url { get; set; }
    }
}
