//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITC.CMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Settings = new HashSet<Setting>();
        }
    
        public System.Guid ModuleID { get; set; }
        public string ModuleName { get; set; }
        public bool Inactive { get; set; }
        public bool IsSystem { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<Setting> Settings { get; set; }
    }
}
