//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITC.CMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int PageID { get; set; }
        public string PageTitle { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string Body { get; set; }
        public string Template { get; set; }
        public string Url { get; set; }
        public bool Inactive { get; set; }
        public int SortOrder { get; set; }
        public string Culture { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
