//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITC.CMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public Portfolio()
        {
            this.PortfolioImages = new HashSet<PortfolioImage>();
            this.PortfolioCategories = new HashSet<PortfolioCategory>();
        }
    
        public int PortfolioID { get; set; }
        public string PortfolioName { get; set; }
        public string Description { get; set; }
        public string Culture { get; set; }
        public int SortOrder { get; set; }
        public bool Inactive { get; set; }
        public bool IsFeatured { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string Location { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<PortfolioImage> PortfolioImages { get; set; }
        public virtual ICollection<PortfolioCategory> PortfolioCategories { get; set; }
    }
}
